### PR TITLE
Fix issue #24: retain image position on coming back to edit again.

### LINKED ISSUE #24: Bug: Slider position reverts to original while coming back to edit again
I uploaded image from link then dragged down and resized with help of slider and finalized the signature. But when I came back to edit again, the values of dragged/scaled item resets to default.

Final
On back Selection

### PR DESCRIPTION
**Pull request by anoopmsivadas**
Add position state for React Avatar Editor to retain the image position even after going back to edit again.
Fixes #24

### CODE REVIEW

**Review by abhir9 — APPROVED** [review]

**Comment by abhir9** [comment]
@anoopmsivadas Your PR merged

Thanks for your contribution
don't forget to star the repo

apart from this, offering you swags from loginradius , please fill this form
https://docs.google.com/forms/d/e/1FAIpQLSfnwWUWlRRwZpgmOX7X8lGMKotLbVe1JXCjPFSahLxLWugwig/viewform

**Comment by pareek-naren** [comment]
@anoopmsivadas 
We are going to feature our top contributors on the LoignRadius social media platform.
If you are interested, please share your LinkedIn, Twitter Profile along with the image you wanted to display.

**Comment by anoopmsivadas** [comment]
@pareek-narendra where should I share those?

**Comment by abhir9** [comment]
@anoopmsivadas you can share here .

**Comment by anoopmsivadas** [comment]
Ok,
 LinkedIn:  https://www.linkedin.com/in/anoopmsivadas/
twitter: https://twitter.com/anoopmsivadas
image: https://twitter.com/AnoopMSivadas/photo (hope this one is fine.)

**Pull request merged**
