### PR TITLE
fix(bug): fix issue with wrong state of edit field

### LINKED ISSUE #3: While edit fields click on done, keep open edit field (should be closed)

### PR DESCRIPTION
**Pull request by daniloff200**
closes #3

### CODE REVIEW

**Comment by abhir9** [comment]
looks good , thanks @daniloff200 !

**Comment by daniloff200** [comment]
I'm wondering, will my 2 PRs be counted as related to Hacktoberfest,  because I've made them 5 days earlier

@abhir9 do you have any info about that?

**Comment by abhir9** [comment]
@daniloff200 I guess, it will not , though issue is reopened now , you can raise another PR to fix that , on or after 1 Oct. Ill assign it to you.

**Comment by vyasriday** [comment]
Hey @daniloff200 Thanks for contributing to LoginRadius Open Source.  Unfortunately, your current PRs won't be counted towards hacktoberfest but they sure count towards LoginRadius Open Source.  Please fill the [form](https://forms.gle/aUYJXoVJVivPgGuM8) to become eligible for LoginRadius swags. Read more about it at our [Engineering Blog](https://www.loginradius.com/engineering/page/hacktoberfest2020)

**Comment by daniloff200** [comment]
@vyasriday  I mostly was worried about LoginRadius :)
Thanks for the answer!

**Pull request merged**
