### PR TITLE
Changes in UI, Update Readme and Contributing

### PR DESCRIPTION
**Pull request by sohamsshah**
The Edits are as follows:

1.
feat: Alert message in App.js
When the user tries to upload an invalid image format, then for better user experience an acknowledgement alert must be provided for smooth usage.

2.
docs: change Readme and Contributing
Add new point in the Features (in Readme.md)
Fix typo spelling of "guarantee" in the Contributing.md

3.
style: Changes in UI
Changed font sizes, margin, color and some other minor changes to beautify the UI and make it consistent.

P.S. This is my first Pull Request for LoginRadius and I wish to be an active contributor in this Project for future scaling up, code, bug fixes, management and new features. Would love to receive feedbacks and guidance from the Core team! Thank you!

### CODE REVIEW

**Comment by abhir9** [comment]
@sohamsshah  

Conflicting files
package.json

**Comment by sohamsshah** [comment]
@abhir9 please check, I have resolved the conflicts. 

P.S. Can you let me know about the contribution I did? Was it proper as per requirement, so I can learn and contribute more towards this project.

**Comment by abhir9** [comment]
PR has conflicts , probably due to recent changes, please resolve them, after that ill resume reviewing process.

**Comment by sohamsshah** [comment]
Hey @abhir9 Actually it is showing that it has no conflicts with base branch. Am I misunderstanding something? Please help me out, I will solve conflicts etc. ASAP and I am quite active right now for contribution in LoginRadius right now. Thank you for responding to my PR 😁😁

**Comment by sohamsshah** [comment]
conflicts

**Comment by sohamsshah** [comment]
@abhir9 Resolved the conflicts...

**Comment by abhir9** [comment]
image

but still i can see

**Comment by abhir9** [comment]
merged now , thanks

**Comment by sohamsshah** [comment]
@abhir9 Thank you so much. This made my Sunday! Looking forward for more amazing work in this project!

**Pull request merged**
